### ISSUE TITLE
confirm clear/reindex

### ISSUE THREAD

**Issue by BenLubar** [barisusakli/nodebb-plugin-dbsearch#19]
Clicking the buttons on the search settings page can cause a forum to be inaccessible for several hours. It'd be nice if there was a confirmation dialog to avoid accidental reindexing of hundreds of thousands of posts.

**Comment by julianlam** [comment]
@BenLubar Yes, that's not exactly the best UX there... My solr search plugin suffers from the same problem.

There should probably just be some sort of throttler (if on a single process), or some usage of `fork` if multiple processes are detected on the host system...

That, and persisting to the database in batches, instead of at the very end. (That's a Solr thing, not sure if dbsearch does that as well)

**Comment by barisusakli** [comment]
This is still happening 1.0.0 of this plugin right?

**Comment by BenLubar** [comment]
@barisusakli Yes. I found this yesterday on an EC2 instance of 1.0.0 (actually, `master` from a few days ago), but it seems to be more responsive on a local instance - possibly because EC2 throttles the number of disk I/O operations per second.
